# Generated by Django 3.1.7 on 2021-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0002_auto_20210330_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selectedqnt',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
