# Generated by Django 3.1.7 on 2021-04-01 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0003_auto_20210331_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 5, 43, 29, 303474)),
        ),
    ]
