# Generated by Django 3.1.7 on 2021-04-02 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0004_auto_20210401_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 5, 43, 29, 560020)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selectedqnt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
