# Generated by Django 3.1.7 on 2021-04-02 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0005_auto_20210402_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('availquantity', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 0, 16, 641996)),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='productmeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineCartApp.productsmeta'),
        ),
    ]
