# Generated by Django 3.1.7 on 2021-04-03 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0006_auto_20210402_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 7, 46, 20, 555409)),
        ),
    ]
