# Generated by Django 3.1.7 on 2021-04-03 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0007_auto_20210403_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='productmeta',
        ),
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 1, 24, 480909)),
        ),
    ]
