# Generated by Django 3.1.7 on 2021-04-03 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0008_auto_20210403_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 17, 56, 20, 373034)),
        ),
    ]
