# Generated by Django 3.1.7 on 2021-04-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0010_auto_20210404_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productowner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='cart',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 8, 46, 58, 548885)),
        ),
    ]
