# Generated by Django 3.1.7 on 2021-03-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210330_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='grandtotal',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subtotal',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tax',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
