# Generated by Django 3.1.7 on 2021-04-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCartApp', '0007_auto_20210403_0746'),
        ('Product', '0003_auto_20210331_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderprod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineCartApp.productsmeta'),
        ),
    ]
