# Generated by Django 3.1.7 on 2021-04-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210403_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='purchaseprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='productmeta',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='selqnt',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='grandtotal',
            new_name='total',
        ),
    ]
