# Generated by Django 3.1.7 on 2021-04-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210404_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderuser',
            new_name='user',
        ),
    ]
